//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSTE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSTE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to —
        ///Stench
        ///Drizzle
        ///Speed Boost
        ///Battle Armor
        ///Sturdy
        ///Damp
        ///Limber
        ///Sand Veil
        ///Static
        ///Volt Absorb
        ///Water Absorb
        ///Oblivious
        ///Cloud Nine
        ///Compound Eyes
        ///Insomnia
        ///Color Change
        ///Immunity
        ///Flash Fire
        ///Shield Dust
        ///Own Tempo
        ///Suction Cups
        ///Intimidate
        ///Shadow Tag
        ///Rough Skin
        ///Wonder Guard
        ///Levitate
        ///Effect Spore
        ///Synchronize
        ///Clear Body
        ///Natural Cure
        ///Lightning Rod
        ///Serene Grace
        ///Swift Swim
        ///Chlorophyll
        ///Illuminate
        ///Trace
        ///Huge Power
        ///Poison Point
        ///Inner Focus
        ///Magma Armor
        ///Water Veil
        ///Magnet Pull
        ///Soundproof
        ///Rain Dish
        ///Sand Stream
        ///Pressure
        ///Thick Fat
        ///Ear [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Abilities_en {
            get {
                return ResourceManager.GetString("text_Abilities_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///One
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Kyogre
        ///Groudon
        ///
        ///
        ///Normal
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Plant
        ///Plant
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Overcast
        ///West Sea
        ///West Sea
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Forms_en {
            get {
                return ResourceManager.GetString("text_Forms_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice
        ///Sacred Ash
        ///HP Up
        ///Protein
        ///Iron
        ///Carbos
        ///Calci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ———
        ///Pound
        ///Karate Chop
        ///Double Slap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///Vice Grip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonic Boom
        ///Disable
        ///Acid
        ///Ember
        ///Flamethrower
        ///Mist
        ///Water Gun
        ///Hydro  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Moves_en {
            get {
                return ResourceManager.GetString("text_Moves_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        ///Psyduck
        ///Golduck
        ///Mankey
        ///Primeape
        ///Growlithe
        ///Arcanine
        ///Pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Trainer
        ///Pokémon Trainer
        ///Youngster
        ///Lass
        ///Leader
        ///Sky Trainer
        ///Sky Trainer
        ///Waitress
        ///Ace Duo
        ///Ace Trainer
        ///Ace Trainer
        ///Preschooler
        ///Preschooler
        ///Hex Maniac
        ///Lady
        ///Beauty
        ///Rich Boy
        ///Swimmer ♂
        ///Team Flare
        ///Team Flare
        ///Team Flare
        ///Team Flare
        ///Team Flare
        ///Black Belt
        ///Tourist
        ///Garçon
        ///Artist Family
        ///Artist
        ///Artist
        ///Scientist
        ///Scientist
        ///Psychic
        ///Worker
        ///Worker
        ///Butler
        ///Elite Four
        ///Elite Four
        ///Elite Four
        ///Elite Four
        ///Leader
        ///Leader
        ///Leader
        ///Leader
        ///Leader
        ///Leader
        ///Leader
        ///Brains &amp; Brawn
        ///Punk Guy
        ///Scho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_TrainerClasses_en {
            get {
                return ResourceManager.GetString("text_TrainerClasses_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -
        ///Brendan
        ///Brendan
        ///Brendan
        ///May
        ///May
        ///May
        ///Calvin
        ///Rick
        ///Lyle
        ///Tiana
        ///Daisy
        ///Amy &amp; Liv
        ///Andrew
        ///Ivan
        ///Claude
        ///Billy
        ///Haley
        ///Jerry
        ///Karen
        ///Grunt
        ///Grunt
        ///Tommy
        ///Joey
        ///Jose
        ///Janice
        ///Luis
        ///Austin
        ///Beverly
        ///Dawn
        ///Douglas
        ///Nicole
        ///Elliot
        ///Ned
        ///Kirk
        ///Shawn
        ///Darrin
        ///Tony
        ///Denise
        ///Beth
        ///Jerome
        ///Matthew
        ///Tara
        ///Missy
        ///David
        ///Alice
        ///Huey
        ///Edmond
        ///Lola
        ///Jacob
        ///Anthony
        ///[~ 51]
        ///[~ 52]
        ///Edwin
        ///Dale
        ///Amy &amp; Liv
        ///Hideki
        ///Hitoshi
        ///Kiyo
        ///Tessa
        ///Laura
        ///[~ 61]
        ///[~ 62]
        ///Randall
        ///Parker
        ///George
        ///Berke
        ///Mary
        ///Lori
        ///Jody
        ///[~ 70]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_TrainerNames_en {
            get {
                return ResourceManager.GetString("text_TrainerNames_en", resourceCulture);
            }
        }
    }
}
